CREATE TABLE public.admin (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL,
  CONSTRAINT pk_admin PRIMARY KEY (id)
);

ALTER TABLE public.admin ADD CONSTRAINT uc_admin_email UNIQUE (email);
ALTER TABLE public.admin ADD CONSTRAINT uc_admin_token UNIQUE (token);

CREATE TABLE public.employee (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL,
  last_attendance_date TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT pk_employee PRIMARY KEY (id)
);

ALTER TABLE public.employee ADD CONSTRAINT uc_employee_email UNIQUE (email);
ALTER TABLE public.employee ADD CONSTRAINT uc_employee_token UNIQUE (token);