ALTER TABLE employee DROP COLUMN last_attendance_date;

CREATE TABLE public.attendance (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  date TIMESTAMP WITHOUT TIME ZONE,
  employee_id INTEGER,
  CONSTRAINT pk_attendance PRIMARY KEY (id)
);

ALTER TABLE public.attendance ADD CONSTRAINT FK_ATTENDANCE_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES public.employee (id);